[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-app-name.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-app-name.onrender.com"