services:
  - type: web
    name: ai-career-recommendation
    env: node
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.17.0